#!/bin/sh

cd /home/tangjifan/10.24/lad-crawler/lad

echo `date '+%Y-%m-%d %H:%M:%S'` >> runtime.log
scrapy crawl 39newnew &
scrapy crawl 39health1new &
scrapy crawl 39health2new &
scrapy crawl 39health3new &
scrapy crawl 39health4new &
scrapy crawl 39health5new &
scrapy crwal 39health6new &
scrapy crwal 39health7new &
scrapy crwal 39health8new &
scrapy crawl feihua1new &
scrapy crawl feihua2new &
scrapy crawl 99yijinew &
scrapy crawl 99yiji2new &
scrapy crawl dazhongyangshengwangnew &
scrapy crawl dazhongyangshengwang2 &
scrapy crawl yanhuang2 &
scrapy crawl yanhuang3 &
scrapy crawl yanhuang4 &
scrapy crawl 99yangshengwangnew &
scrapy crawl 99yangshengwangnew2 &
scrapy crawl shenzhennew &
scrapy crawl beijingnew &
scrapy crawl lasanew &
scrapy crawl lanzhounew &
scrapy crawl qinghainew &
scrapy crawl kunmingnew &
scrapy crawl neimenggunew &
scrapy crawl sichuannew &
scrapy crawl guangxinew &
scrapy crawl nanjingnew &
scrapy crawl jinannew &
scrapy crawl hangzhou_new &
scrapy crawl beijinggongan1 &
scrapy crawl beijinggongan2 &
scrapy crawl gonganbu1 &
scrapy crawl gonganbu2 &
scrapy crawl shanghaigongan &
scrapy crawl guangzhougongan &
scrapy crawl jilin_new &
scrapy crawl jiangsugongan &
scrapy crawl jiangsugongan2 &
scrapy crawl changchun_new &
scrapy crawl hlj_new &
scrapy crawl sx_new &
scrapy crawl guangdonggongan1 &
scrapy crawl guangdonggongan2 &
scrapy crawl hebeigongan &
scrapy crawl taiyuan_new &
scrapy crawl hubei_new &
scrapy crawl haikou_new &
scrapy crawl zhejianggongan1 &
scrapy crawl jinangongan &
scrapy crawl liaoninggongan &
scrapy crawl changsha_new &
scrapy crawl chinanews_1 &
scrapy crawl shebaopindao &
scrapy crawl shebaopindao2 &
scrapy crawl shebaowang1 &
scrapy crawl shebaowang2 &
scrapy crawl shebaowang3 &
scrapy crawl shebaowang4 &
scrapy crawl shebaowang56 &
scrapy crawl fengwang &
scrapy crawl yanglaoxinxiwang1 &
scrapy crawl yanglaoxinxiwang2 &
scrapy crawl yanglaoxinxiwang3 &
scrapy crawl yanglaoxinxiwang4 &
scrapy crawl yanglaoxinxiwang5 &
scrapy crawl yanglaoxinxiwang6 &
scrapy crawl shanghailaolingwang1 &
scrapy crawl shanghailaolingwang2 &
scrapy crawl shanghailaolingwang3 &
scrapy crawl shanghailaolingwang4 &
scrapy crawl nanbeichaowang &
scrapy crawl shandonglaolingban1 &
scrapy crawl shandonglaolingban2 &
scrapy crawl shandonglaolingban3 &
scrapy crawl shandonglaolingban4 &
scrapy crawl shanghaiyanglaowang1 &
scrapy crawl shanghaiyanglaowang2 &
scrapy crawl chinanews_1 &
scrapy crawl huanqiuwang_2 &
scrapy crawl shanxilaolingwang1 &
scrapy crawl shanxilaolingwang2 &
scrapy crawl huanqiuwang_1 &
scrapy crawl huanqiuwang_3 &
scrapy crawl yanglaowang &
scrapy crawl quanguolaolingban1 &
scrapy crawl quanguolaolingban2 &
scrapy crawl quanguolaolingban3 &
scrapy crawl quanguolaolingban4 &
scrapy crawl quanguolaolingban5 &
scrapy crawl quanguolaolingban6 &
scrapy crawl quanguolaolingban7 &
scrapy crawl anhuilaolingban1 &
scrapy crawl anhuilaolingban2 &
scrapy crawl anhuilaolingban3 &
scrapy crawl anhuilaolingban4 &
scrapy crawl anhuilaolingban5 &
scrapy crawl anhuilaolingban6 &
scrapy crawl anhuilaolingban7 &
scrapy crawl anhuilaolingban8 &
scrapy crawl xiamenlaolingwang1 &
scrapy crawl xiamenlaolingwang2 &
scrapy crawl haikoulaolingban1 &
scrapy crawl haikoulaolingban2 &
scrapy crawl beijingdaxing &
scrapy crawl renminwang_zhengzhi1 &
scrapy crawl chengdulaolinggongzuowang1 &
scrapy crawl chengdulaolinggongzuowang2 &
scrapy crawl guangdonglaolingchanyexihui1 &
scrapy crawl guangdonglaolingchanyexihui2 &
scrapy crawl guangdonglaolingchanyexihui3 &
scrapy crawl guojilaonianwang1 &
scrapy crawl guojilaonianwang2 &
scrapy crawl guojilaonianwang3 &
scrapy crawl guojilaonianwang4 &
scrapy crawl guojilaonianwang5 &
scrapy crawl henanshenglaonianwang1 &
scrapy crawl henanshenglaonianwang2 &
scrapy crawl henanshenglaonianwang3 &
scrapy crawl renminwang_guoji1 &
scrapy crawl jilinlaolingban1 &
scrapy crawl jilinlaolingban2 &
scrapy crawl jilinlaolingban3 &
scrapy crawl jilinlaolingban4 &
scrapy crawl hebeilaolinggongzuoweiyuanhui1 &
scrapy crawl hebeilaolinggongzuoweiyuanhui2 &
scrapy crawl hebeilaolinggongzuoweiyuanhui3 &
scrapy crawl lishuilaolingwang1 &
scrapy crawl lishuilaolingwang2 &
scrapy crawl lishuilaolingwang3 &
scrapy crawl lishuilaolingwang4 &
scrapy crawl ningxialaolingban1 &
scrapy crawl ningxialaolingban2 &
scrapy crawl ningxialaolingban3 &
scrapy crawl xinjianglaolingban1 &
scrapy crawl xinjianglaolingban2 &
scrapy crawl xinjianglaolingban3 &
scrapy crawl xinjianglaolingban4 &
scrapy crawl renminwang_jingji &
scrapy crawl guangdonglaolingwang1 &
scrapy crawl guangdonglaolingwang2 &
scrapy crawl guangdonglaolingwang3 &
scrapy crawl shaoxinglaolingwang1 &
scrapy crawl shaoxinglaolingwang2 &
scrapy crawl shaoxinglaolingwang3 &
scrapy crawl shaoxinglaolingwang4 &
scrapy crawl renminwang_military &
scrapy crawl huaianqulaolingwang1 &
scrapy crawl huaianqulaolingwang2 &
scrapy crawl xiangrikuibaoxianwang1 &
scrapy crawl xiangrikuibaoxianwang2 &
scrapy crawl guangzhoulaolingwang1 &
scrapy crawl guangzhoulaolingwang2 &
scrapy crawl renminwang_society &
scrapy crawl renminwang_sports1 &
scrapy crawl dezhoulaolingban1 &
scrapy crawl dezhoulaolingban2 &
scrapy crawl dezhoulaolingban3 &
scrapy crawl jiangximinzhengwang1 &
scrapy crawl jiangximinzhengwang2 &
scrapy crawl jiujianglaolingwang1 &
scrapy crawl jiujianglaolingwang2 &
scrapy crawl liaoningchaoyanglaolingwang &
scrapy crawl xinhuawang_zhengzhi1 &
scrapy crawl xinhuawang_guoji1 &
scrapy crawl xinhuawang_guoji2 &
scrapy crawl xinhuawang_guoji3 &
scrapy crawl xinhuawang_guoji4 &
scrapy crawl xinhuawang_guoji5 &
scrapy crawl xinhuawang_guoji6 &
scrapy crawl haimenlaolingwang &
scrapy crawl hainanzhengfu &
scrapy crawl hanshouxianzhengfu &
scrapy crawl harbinlaolingban1 &
scrapy crawl harbinlaolingban2 &
scrapy crawl hunanshengweilaoganbuju &
scrapy crawl quanzhou &
scrapy crawl shenzhenshebao &
scrapy crawl xinhuawang_guoji7 &
scrapy crawl xinhuawang_guoji8 &
scrapy crawl xinhuawang_sports &
scrapy crawl xinhuawang_military &
scrapy crawl xinhuawang_economy &
scrapy crawl xinhuawang_society1 &
scrapy crawl xinhuawang_society2
